### PR TITLE
fix: show zsh description

### PR DESCRIPTION
**Pull request by ysndr**
reset the compadd argument list for every command

### CODE REVIEW

**Comment by ysndr** [comment]
Zsh completions were showing no descriptions, but `show` and `arg0`
Seems like the `cmd` array that is passed as arguments to `compadd` was not reset and contains invalid items causing completions to fail showing descriptions at all

**Comment by pacak** [comment]
I'm using zsh and it seem to work as expected for me

Or is it something I'm missing here?

```
elakelaiset% cargo-asm <TAB>
--all-features    Activate all available features
--att    Show assembly using AT&T style
--bench <BENCH>    Show results from a benchmark
--bin <BIN>    Show results from a binary
--color    Enable color highlighting
--dev    Compile in dev mode
--dry    Produce a build plan instead of actually building
--everything    Dump the whole asm file
--example <EXAMPLE>    Show results from an example
--features <FEATURE>    A feature to activate, can be used multiple times
--frozen    Requires Cargo.lock and cache are up to date
--full-name    Include full demangled name instead of just prefix
<FUNCTION>    Dump function with that specific name / filter functions containing this string
--intel    Show assembly using Intel style
<ITEM_INDEX>    Dump name with this index
--keep-labels    Keep all the original labels
--lib    Show results from library code
--llvm    Show llvm-ir
--locked    Requires Cargo.lock is up to date
--manifest-path <PATH>    Path to Cargo.toml
--mir    Show MIR
--native    Optimize for the CPU running the compiler
--no-color    Disable color highlighting
--no-default-features    Do not activate `default` feature
--offline    Run without accessing the network
--package <SPEC>    Package to use if ambigous
--profile <PROFILE>    Build for this specific profile
--release    Compile in release mode (default)
--rust    Print interleaved Rust code
--simplify    Try to strip some of the non-assembly instruction information
--target-cpu <CPU>    Optimize code for a specific CPU, see 'rustc --print target-cpus'
--target-dir <DIR>    Use custom target directory for generated artifacts, create if missing
--target <TRIPLE>    Build for the target triple
--test <TEST>    Show results from a test
--verbose    more verbose output, can be specified multiple times
--wasm    Show WASM, needs wasm32-unknown-unknown target installed
```

**Comment by ysndr** [comment]
What if you remove the description from one of the flags?

**Comment by ysndr** [comment]
if I omit the description for one of the flags (debug in my case) it shows this:

```
myprog <tab>
--         --debug    --verbose  -d         myprog       show   
```

**Comment by pacak** [comment]
> with that change it shows

`zsh` will try to render things in multiple columns if lines are narrow enough. I can get similar output from `cargo-show-asm` if I widen my terminal enough.

**Comment by ysndr** [comment]
Oh yes its not about the column style

see how the former also completes `myprog` and `show` as well as not showing any description at all

**Comment by pacak** [comment]
Hmm... I see no difference here, but since there's no point in keeping `cmd` across different lines - let's merge this :+1: 

Will release along with man page stuff when it's done.

**Comment by ysndr** [comment]
btw are completions *supposed* to show short versions of flags?

**Comment by pacak** [comment]
It prefers displaying long flags when available and will expand short flag to long when possible: `foo -d<TAB>` => `foo --debug`, etc. But will show short flag if long one is not present.

**Comment by ysndr** [comment]
yes thats what i found as well, but for USAGE strings the behaviour is opposite right?

just wondering if both options should be shown if present?

**Comment by pacak** [comment]
For usage - it's short options to keep things compact.

**Pull request merged**
