### PR TITLE
Remove angle brackets around placeholders from completion

### PR DESCRIPTION
**Pull request by ysndr**
Some shells will escape the angle brackets
used around the placeholders do something like `\<ARG\>` as `<` and `>` are special characters

One more..

Perhaps it's my zsh config trying to be too helpful for it own good, but i think

```
myprog run --verbosity \<VERBOSITY\> \<ARG\> 
```

does not look as appealing

this changes it to 

```
myprog run --verbosity VERBOSITY ARG 
```

### CODE REVIEW

**Comment by pacak** [comment]
Is it something zsh inserts in the command line or just proposes to complete? It should be proposing with angular brackets to indicate that this is a placeholder but shouldn't be completing them. At least I never saw it completing anything escaped. Can you share option definition that results in this completion?

**Comment by ysndr** [comment]
Reproduction
```
use bpaf::Bpaf;

fn main() {
    app().run();
}


#[derive(Debug, Bpaf)]
#[bpaf(options)]
struct App {
    #[bpaf(short, long, argument("VERBOSITY"))]
    verbosity: String
}
```

**Comment by ysndr** [comment]
Fyi, this also seems to happen in `fish`

**Comment by jirutka** [comment]
There’s a widespread convention that lower-case arguments are formatted in angle braces and upper-case arguments without braces. Can you please update this PR to drop angle braces only for upper-case arguments?

**Comment by pacak** [comment]
> There’s a widespread convention that lower-case arguments are formatted in angle braces and upper-case arguments without braces.

Do you have any examples? I'm not sure how to look for this kind of stuff :)

**Comment by pacak** [comment]
Cargo prints `<>` for capital letters. not for completion though.

```console
% cargo run --release --exampl
error: Found argument '--exampl' which wasn't expected, or isn't valid in this context

  Did you mean '--example'?

Usage: cargo run --release --example [<NAME>] [args]...

For more information try '--help'
```

**Comment by jirutka** [comment]
> Do you have any examples? I'm not sure how to look for this kind of stuff :)

For example, http://docopt.org/ (at the bottom of the page). These are basically my empirical findings, I don’t know of any resources off the top of my head.

**Comment by jirutka** [comment]
I just noticed that generated usage doesn’t use angel braces.

```
Usage: [--timeout msec]

    --timeout <msec>  ...
```

It would be better to be consistent:

```
Usage: [--timeout <msec>]
```

**Comment by jirutka** [comment]
Wait a moment; this PR is just about completion, not --help in general… Everything I’ve written is to --help message for humans, not to the completion parsers; I have no idea what they expect.

**Comment by pacak** [comment]
Closest thing to specification https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/basedefs/V1_chap12.html mentions them but without distinction for capital or small letters. `cargo` uses them with capital letters.

> Everything I’ve written is to --help message for humans, not to the completion parsers; I have no idea what they expect.

Yea, slightly different thing. Completion parsers just pass it to user so it's about what user will get on pressing TAB when there's ambiguities.

**Comment by pacak** [comment]
> I just noticed that generated usage doesn’t use angel braces.

usage line uses `<>` for positional items: `--test FOO` is an argument `--test` with metavar `FOO`, `--test <FOO>` is a flag `--test` and positional item `FOO`.

**Comment by ysndr** [comment]
Even though its aside this PR:

> usage line uses <> for positional items: --test FOO is an argument --test with metavar FOO, --test <FOO> is a flag --test and positional item FOO.

When creating multivalue options i.e. `--flag a b` per the documented approach you end up with `--flag <a> <b>` which renders differently then an option with a single argument `--flag a`. At that point for consistency I had to implement a single value flag as a custom parser as well just to get the same layout `--flag <a>`.

**Comment by pacak** [comment]
Let's get back to this after the documentation generation stuff.

**Comment by ysndr** [comment]
Sure, I'm just logging this here for posterity.

**Comment by pacak** [comment]
@ysndr I'm making a big cosmetic cleanup, will most likely include this change as well, tried to address most of your cosmetic suggestions do. I saw you've been using this branch somewhere in your code. Do you have any other changes you would like to get in?

**Comment by pacak** [comment]
https://github.com/pacak/bpaf/pull/216 - new branch is going to be here

**Comment by ysndr** [comment]
> I saw you've been using this branch somewhere in your code.

I've been using a fork at #155 for the time being

> Do you have any other changes you would like to get in?

I'll try out #216 and see if I miss something

**Comment by pacak** [comment]
Angle brackets around placeholders are mostly gone and completion system was reimplemented so that it won't complete metavar placeholders

**Pull request closed without merging**
