### PR TITLE
Add `try_run` method

### PR DESCRIPTION
**Pull request by ysndr**
Currently interactive parsing and error recovery is not possible at the same time is not possible.
`try_run` addresses that.

### CODE REVIEW

**Comment by pacak** [comment]
Hmm... `try_run` is basically a combination of public `run_inner` and public `From<&[OsStr]>` `Args` instance. Can you explain a bit more about interactive parsing and error recovery you are doing? Do you have any code publicly available?

**Comment by ysndr** [comment]
Sorry, I have no code public for that yet, but basically what I want is

- autocompletion support
- control over when and how to exit

I used to use clap's [`try_parse`](https://docs.rs/clap/latest/clap/trait.Parser.html#method.try_parse) method before but found that that's not available in bpaf

**Comment by pacak** [comment]
I see. Autocompletion support is a bit more annoying in that case. I guess we can get this in. What kind of cleanup do you have in mind? What's the practical example? Usually you'd run it before anything else starts so no cleanup is needed. Do you have something that replaces regular `main` such as `tokio`?

**Comment by ysndr** [comment]
So for reasons I am unlikely to change, my autocomplete implementation might have some side effects that need to be cleaned up.

No control over the error code returned is also unfortunate IMO

**Comment by pacak** [comment]
doctests are still broken.

**Comment by ysndr** [comment]
Failing on `error: unknown lint: 'rustdoc::missing_doc_code_examples'` now 🤔

**Comment by pacak** [comment]
Mystery. I'll take a closer look tomorrow.

**Comment by pacak** [comment]
Merged to master, ended up removing the lint. Will try to release a new version in a few days

**Pull request merged**
