### PR TITLE
Provide `pure_with` parser

### LINKED ISSUE #79: Question: Default/Fallback for many/some?
Hello, first of all many thanks for this beautiful library!

I was wondering how I could achieve providing a calculated default for a `.many()` parser as demonstrated in the following test. (I also tried using `.some(..)` but that fails as well :/) Any ideas?

```rust
    #[test]
    fn default_positional() {
        use bpaf;

        let roots = bpaf::positional::<String>("ROOTS")
            .fallback_with::<_, String>(|| Ok(String::from(".")))
            .many();

        struct Roots { roots: Vec<String>, }

        let r = construct!(Roots {roots}).to_options().run_inner(Args::from(&[]));
        assert_eq!(vec![String::from(".")], r.unwrap().roots);
    }
```

### PR DESCRIPTION
**Pull request by xitep**
* Adds a `pure_with` parser to be the lazily computed, fallible equivalent to `pure`
* Resolves #79

### CODE REVIEW

**Comment by pacak** [comment]
Change looks useful but we need to think about explaining to users where `pure_with` fits:

:x: Example in the lib.rs is not going to work - switch never fails, so both branches succeed. When there is a parameter - switch wins since it's "left most item on a command line", when there's no parameter - switch still wins because it's the "left most item inside construct". 

:x: It can be used as a fallback to `many`, but you need to place it _before_ `many` in a choice constructor and it will be evaluated anyway (see choice construct docs) - to produce less confusing error message, so behavior would be identical to `pure`.

:x: It can be used as a fallback to `some`, but the idea of `some` is to ask _user_ to provide at least one item, adding fallback to it negates this property. Plus similar to `many` - behavior is going to be identical to `pure`

:heavy_check_mark: It can be used to put a value into a struct field that doesn't get created in every case, something like one extra value in `Action::Hack`: https://github.com/pacak/hackerman/blob/master/src/opts.rs#L20

:heavy_check_mark: It can be used to put a result of failing computation into a struct or choice without having to deal with `fail` and boxing manually. `pure_with` shows the intent better.

I need a bit more time to think about it

**Comment by xitep** [comment]
* admitted, the example in `lib.rs` is artificial. i can improve on that, of course.
* ideally, `some` would fail with `Error:Missing` carrying along the custom error message instead of failing with `Error::Stderr(self.message.to_string())` - if i understand the logic correly, that would mail `fallback_with` trigger and provide its value. unfortunately i couldn't get this working (due to lack of rust and bpaf knowledge.)

**Comment by pacak** [comment]
> admitted, the example in lib.rs is artificial. i can improve on that, of course.

Yea, once we understand the usage example is not a problem.

> ideally, `some` would fail with Error:Missing carrying along the custom error message instead of failing with Error::Stderr(self.message.to_string()) 

:thinking: Interesting idea. This might work in some cases, problem is `some` is more generic than just consuming any structure multiple times: https://github.com/pacak/bpaf/blob/master/examples/sensors.rs#L73 - this line could be `some` asking user to specify at least one sensor. At the end of the run `bpaf` colllects all the missing bits and asks user to specify one of them. Having errors from `some` there seems confusing. I'll experiment a bit.

> if i understand the logic correly, that would mail fallback_with trigger and provide its value. 

Right, that's how it might work with both `fallback` and `fallback_with`.

**Comment by pacak** [comment]
I'll take it but will replace bits of the documentation.

**Pull request merged**
