### PR TITLE
Use a full sentence to report error messages

### PR DESCRIPTION
**Pull request by pacak**
```diff
-"Expected `A`, pass `--help` for usage information"
+"Error: expected `A`, pass `--help` for usage information"
```

### CODE REVIEW

**Comment by pacak** [comment]
Hmm.... I'm going off this feedback: https://lemmyrs.org/post/117231

Currently it's not clear if "`--intel` cannot be used with `--att`" is an error or not. Most of the cli apps I poked around use "Error" prefix in some form.

```text
% cargo --no-such-item
error: unexpected argument '--no-such-item' found

Usage: cargo [+toolchain] [OPTIONS] [COMMAND]

For more information, try '--help'.
```

**Comment by pacak** [comment]
> that is unless the Error: bit is only inserted by the default runner, I couldnt quite tell from the diff

It is always included.

> It's quite common for consumers to pass these error messages through a standard logging system where you would easily end up with:

By that you mean using it with `run_inner` and handling errors from there? Are you doing something like this? Any examples?

**Comment by ysndr** [comment]
Yeah i get their ask for an "error: " prefix, but i consider that a detail to be left to the cli application not the argument parser (the parser can have a convenience method to run and exit on errors with an opinionated error style)

> By that you mean using it with run_inner and handling errors from there? 

Yes, exactly.

I want to be able to do

```rust
match command.run_inner() {
   Ok(args) => do_something_with(args),
   Err(bpaf::ParseFailure::Stdout(ref e)) => {
     log::info!("{e}");
     exit(0);
   },
   Err(bpaf::ParseFailure::Stderr(ref e)) => {
     log::error!("{e}");
     exit(1);
   }
}
```

**Comment by pacak** [comment]
> but i consider that a detail to be left to the cli application not the argument parser.

I'm not sure. As a library developer I'm trying to provide a user friendly error message, as a library user I don't even initialize the logger until I get verbosity levels from the command line. It's `options().run()` and then I start the logger - probably because I tend to use `tracing` which won't print anything if you try to log it and immediately exit since it runs in a separate thread.


> I want to be able to do

What's the motivation for that? You will be missing out on colorization goodies added in 0.8/0.9, there will be occasional breaking changes... Like right now I added a separate branch for autocomplete since I need more control on formatting there.

**Comment by ysndr** [comment]
In case of the `options().run()` workflow I would consider that convenience which should print some sort of prefix showing it's an error.

If I use `run_inner()` however I want to retain a bit more control over the output.

Regarding the logging, we actually parse the args twice, first only looking for logging related options and then once more for the whole argument set.
I used to like how clap actually gives you an error struct rather than a final error string when you run it non interactively..

**Comment by pacak** [comment]
> In case of the `options().run()` workflow I would consider that convenience which should print some sort of prefix showing it's an error.

> If I use run_inner() however I want to retain a bit more control over the output.

I guess I can move the prefix printing into `run` or whatever I'm using to print stuff currently, but how much control do you want? Just the prefix? Ability to render the whole error message from AST? I'm planning to render more information inside error messages at some point once I figure out  how to do it the best way, see #221...

> gives you an error struct rather than a final error string when you run it non interactively..

It's not quite an error struct but an error enum with a whole lot of variants that would probably be marked non_exhaustive or even just randomly change within otherwise semver compatible change, do you really want to deal with it?

https://github.com/pacak/bpaf/blob/master/src/error.rs

**Comment by ysndr** [comment]
För the time being the bringing my own prefix in the run_inner case is enough. I don't mean to tweak too much about the error content Just yet...


There are some situations where you would like to, e.g translations, unifying your product ux or structured logging/tracing.

**Pull request merged**
