### PR TITLE
fix: show more suggestions

### PR DESCRIPTION
**Pull request by ysndr**
reg https://github.com/pacak/bpaf/issues/154

I don't quite get why `should_suggest` requires `flgs` to be empty - in fact if there are flags it should indeed suggest is my opinion.

This change makes the error message more correct in most cases i came across.

It's still not perfect, the suggestions are not filtered by what is already given.

like in my example in https://github.com/pacak/bpaf/issues/154:

```
$ notgit log --oneline --doesnotexist
No such flag: `--doesnotexist`, did you mean `--oneline`?
```

Though it does also honor `hide()` correctly.

### CODE REVIEW

**Comment by ysndr** [comment]
> Btw, any preference for API, line 19 vs line 20?
>[pacak/semantic@semantic/src/semantic.rs#L18](https://github.com/pacak/semantic/blob/semantic/src/semantic.rs?rgh-link-date=2023-01-16T14%3A16%3A20Z#L18)

Cool project👀!

I think 

```
doc.paragraph([text("Program takes "), literal("--help"), text(" argument")]);
```

is better for a public api as rustdoc will list the intended options.

The `AddAssign` seems useful to add custom blocks of text.

**Comment by pacak** [comment]
> The `AddAssign` seems useful to add custom blocks of text.

Right, but then repbuilding option lists is all about custom blocks of text...

**Comment by ysndr** [comment]
- `render_to_manpage(&self, title: &str, section: Section, extra: &[&str])`
  I think the extras should be named, but five arguments seems a bit excessive
  Did you consider putting title section and extras into a defaultable struct, and just pass that in here?

- 
	```
	doc.subsection("Finding code to analyze");
	doc += paragraph([
	   ...
	]);
	```
	this looks a bit inconsistent, no?

- when writing markdown you should escape `--` as `\--` as many markdown compilers convert -- to a longer dash char
- these is no more option to generate a manpage for a command?
- **same point**: it would be great to have additional documentation for the command right next to it. With all the markup in `semantic` do you think a conversion from markdown is an option?
- **somewhat unrelated**: esp with cargo-asm-show the usage string gets quote long, perhaps wrapping them heuristically at would be an option?

**Comment by pacak** [comment]
>  `render_to_manpage(&self, title: &str, section: Section, extra: &[&str])`
>  I think the extras should be named, but five arguments seems a bit excessive

Having extras named is harder than it seems - macro accepts any number up to 3 of them including 0, so to properly name them you'd need `Option`, but then there's a check required to make sure first options are filled or everything gets messed up. This way it's up to user to use this correctly. But I'm open to any better suggestions

>    Did you consider putting title section and extras into a defaultable struct, and just pass that in here?

Might work, question is what to default to. `Section::General` should generally work but for extras it's the same problem...

>     doc.subsection("Finding code to analyze");
>     doc += paragraph([
>        ...
>     ]);
>    this looks a bit inconsistent, no?

Totally. I'll see if making it a member function works better, but `+=` is still needed in some cases.

>    when writing markdown you should escape -- as \-- as many markdown compilers convert -- to a longer dash char

If you ask for `literal("--")` inside a paragraph - it will be escaped - see generated help for `cargo-show-asm`. Interestingly enough with `rustdoc` I have to escape it inside a line of text, but not inside `<dl><dt>...`, not sure what's wrong with it

> these is no more option to generate a manpage for a command?

Not implemented yet, but I'll add it back - `cargo-hackerman` is a good ~~victim~~ volunteer to test it :)

> same point: it would be great to have additional documentation for the command right next to it. With all the markup in semantic do you think a conversion from markdown is an option?

Probably. At the moment I'm trying to focus on what you have to provide it, where it comes from is a separate problem. Making some markdown parser a dependency for `semantic` crate might work.

What I'm trying to achieve next is to get this info from doc comments as much as possible so overall workflow looks like you break your options into logical blocks, add doc comments for them, compose them automatically or manually to create chunks of markdown and man pages.

> somewhat unrelated: esp with cargo-asm-show the usage string gets quote long, perhaps wrapping them heuristically at would be an option?

Unrelated and requires extra dependencies to get terminal width. I have a few ideas to how to implement it, but this will have to wait, made #156 for now.


my TODO list for now is something like this
- documentation and API finalization for `semantic`
- adding code to `bpaf` to generate documentation/man pages from `bpaf` primitives
- trying to use this code in several crates of mine to see what works and what does not
- getting `semantic` merged or publish it separately
- getting changes to `bpaf` merged and published.

First 3 items are kind of coupled to gether. Either way here's your opportunity to experiment and make suggestions :)

**Comment by pacak** [comment]
> If the extras are just empty strings? or if they are indeed required an Option<Extras> could work?

It gets rendered to something like this: `.TH title\ with\ spaces 1 extra1 extra2 extra3` with arguments simply being space separated and spaces being escaped. I'm not sure what it would do with just empty strings. Probably need to use `""` in that place? Either way it's one of the bits of the API that can use a bit more thinking, just integration with `bpaf` and ability to (efficiently) render bigger chunks seems more important to me right now.

**Comment by pacak** [comment]
I reimplemented most of the suggestion logic in https://github.com/pacak/bpaf/pull/192, it should be trying to give more suggestions similar to this pull request logic.

**Pull request closed without merging**
